### ISSUE TITLE
Your current bug.

### ISSUE THREAD

**Issue by rdebath** [Shylock-Hg/ABI#4]
I love your crazy little bug.
It **needs** to be tested for!

**Comment by rdebath** [comment]
Okay, I've added the the test to https://github.com/rdebath/Brainfuck/blob/master/bitwidth.b
It should print "Hello World! 255" for an 8bit interpreter like yours, but doesn't.

This little "hello world" also fails on your interpreter.
```bf
+[>[<-[]>+[>+++>[+++++++++++>][>]-[<]>-]]++++++++++<]>
>>>>>----.<<+++.<-..+++.<-.>>>.<<.+++.------.>-.<<+.<.
```

PS: Sorry for the delay, I forgot to merge the change.

**Comment by Shylock-Hg** [comment]
Yes,I know this.This interpreter works worst to brainfuck program which over 1 loop.
And, I will solve this later in break time.

**Comment by Shylock-Hg** [comment]
Solved.
